# Generated by Django 5.2.6 on 2026-06-26 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0008_update_category_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_team', models.CharField(max_length=100, verbose_name='Équipe domicile')),
                ('away_team', models.CharField(max_length=100, verbose_name='Équipe extérieur')),
                ('home_team_code', models.CharField(blank=True, max_length=8)),
                ('away_team_code', models.CharField(blank=True, max_length=8)),
                ('kickoff_at', models.DateTimeField(verbose_name="Coup d'envoi")),
                ('stage', models.CharField(default='Phase de groupes', max_length=100)),
                ('group_name', models.CharField(blank=True, max_length=50, verbose_name='Groupe')),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('finished', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=20)),
                ('predictions_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match CDM',
                'verbose_name_plural': 'Matchs CDM',
                'db_table': 'world_cup_matches',
                'ordering': ['kickoff_at'],
            },
        ),
        migrations.CreateModel(
            name='WorldCupPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('points_earned', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='qr_codes.worldcupmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_cup_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pronostic CDM',
                'verbose_name_plural': 'Pronostics CDM',
                'db_table': 'world_cup_predictions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
